# Generated by CMake 2.8.7

IF("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   MESSAGE(FATAL_ERROR "CMake >= 2.6.0 required")
ENDIF("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
CMAKE_POLICY(PUSH)
CMAKE_POLICY(VERSION 2.6)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
SET(CMAKE_IMPORT_FILE_VERSION 1)

# Create imported target pwp3d
ADD_LIBRARY(pwp3d SHARED IMPORTED)

# Import target "pwp3d" for configuration "Release"
SET_PROPERTY(TARGET pwp3d APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
SET_TARGET_PROPERTIES(pwp3d PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "/pkgs/cuda-6.5/lib64/libcudart.so;/usr/lib/x86_64-linux-gnu/libcuda.so;/pkgs/cuda-6.5/lib64/libnpps.so;/pkgs/cuda-6.5/lib64/libnppi.so;/pkgs/cuda-6.5/lib64/libnpps.so;/u/viper/freeimage/FreeImage/Dist;/u/viper/assimp/assimp-3.1.1/lib"
  IMPORTED_LOCATION_RELEASE "/u/viper/work/tracking/PWP3D/PerseusLib/libpwp3d.so"
  IMPORTED_SONAME_RELEASE "libpwp3d.so"
  )

# Commands beyond this point should not need to know the version.
SET(CMAKE_IMPORT_FILE_VERSION)
CMAKE_POLICY(POP)
